"""Composable training diagnostics and provider extension interfaces."""

# Import built-ins before the orchestrator can resolve its default provider set.
from . import providers as providers
from .binding import bind_training_diagnostic, bind_training_diagnostics
from .class_conditional_quality import (
    ClassConditionalDiffusionQualityDiagnostic,
    DiagnosticClassAllocation,
)
from .config import (
    DiagnosticCadenceConfig,
    DiagnosticSamplingConfig,
    DiffusionQualityConfig,
    ProviderPipelineConfig,
    ProviderSpec,
    ReferencePipelineConfig,
    SamplerProfileConfig,
    TrajectoryProviderConfig,
)
from .contracts import (
    ArtifactRecord,
    BoundTrainingDiagnostic,
    ContextAwareDiagnostic,
    DenoiserArtifactContext,
    DenoiserArtifactProvider,
    DiagnosticBuildContext,
    DiagnosticResult,
    DiagnosticSourceProvider,
    DiagnosticSourceRequest,
    FitStartEvent,
    ProviderValidationContext,
    ReferenceMetricProvider,
    SamplerArtifactContext,
    SamplerArtifactProvider,
    SamplerMetricContext,
    SamplerMetricProvider,
    StepMetricContext,
    StepMetricProvider,
    TrainBatchEndEvent,
    TrainEpochEndEvent,
    TrainingDiagnostic,
    VerifiedMetricSource,
)
from .diffusion_quality import DiffusionQualityDiagnostic
from .registry import DIAGNOSTIC_PROVIDERS, DiagnosticProviderCatalog

__all__ = [
    "DIAGNOSTIC_PROVIDERS",
    "ArtifactRecord",
    "BoundTrainingDiagnostic",
    "ClassConditionalDiffusionQualityDiagnostic",
    "ContextAwareDiagnostic",
    "DenoiserArtifactContext",
    "DenoiserArtifactProvider",
    "DiagnosticBuildContext",
    "DiagnosticCadenceConfig",
    "DiagnosticClassAllocation",
    "DiagnosticProviderCatalog",
    "DiagnosticResult",
    "DiagnosticSamplingConfig",
    "DiagnosticSourceProvider",
    "DiagnosticSourceRequest",
    "DiffusionQualityConfig",
    "DiffusionQualityDiagnostic",
    "FitStartEvent",
    "ProviderPipelineConfig",
    "ProviderSpec",
    "ProviderValidationContext",
    "ReferenceMetricProvider",
    "ReferencePipelineConfig",
    "SamplerArtifactContext",
    "SamplerArtifactProvider",
    "SamplerMetricContext",
    "SamplerMetricProvider",
    "SamplerProfileConfig",
    "StepMetricContext",
    "StepMetricProvider",
    "TrainBatchEndEvent",
    "TrainEpochEndEvent",
    "TrainingDiagnostic",
    "TrajectoryProviderConfig",
    "VerifiedMetricSource",
    "bind_training_diagnostic",
    "bind_training_diagnostics",
    "providers",
]
