"""Training package and public extension contracts."""

from .builder import (
    InferenceAssetProjection,
    ManagedTrainingModule,
    TrainingBuilder,
    TrainingBuilderContext,
    TrainingExecutionBindingBuilder,
    TrainingPlan,
    TrainingPlanAssembly,
    build_training_plan,
    build_training_plan_assembly,
    trainable_parameters,
    training_module_roots,
    validate_training_plan,
)
from .builtin import SupervisedTrainingBuilder, SupervisedTrainingStrategy
from .diagnostics import (
    ClassConditionalDiffusionQualityDiagnostic,
    ContextAwareDiagnostic,
    DiagnosticBuildContext,
    DiagnosticModelAccess,
    FitStartEvent,
    TrainBatchEndEvent,
    TrainEpochEndEvent,
    TrainingDiagnostic,
)
from .ema import ExponentialMovingAverage
from .gaussian import (
    ClassConditionalGaussianDenoisingTrainingBuilder,
    ClassConditionalGaussianDenoisingTrainingStrategy,
    ClassConditionalGaussianDiagnosticSemantics,
    ClassConditionalGaussianStepObservation,
    GaussianDenoisingTrainingBuilder,
    GaussianDenoisingTrainingStrategy,
    GaussianDiagnosticSemantics,
    GaussianStepObservation,
    gaussian_training_target,
)
from .objectives import (
    MSEObjective,
    PerSampleObjective,
    compute_objective,
)
from .optimization import WarmupCosineLR
from .outcome import CheckpointSelectionKind, TrainingRunOutcome
from .precision import (
    PRECISION_KINDS,
    PrecisionKind,
    PrecisionRuntime,
    build_precision_runtime,
    validate_precision_support,
)
from .reporting import FinalSummary, RichTrainingReporter, RunSummary
from .strategy import (
    Batch,
    DeviceTransferableBatch,
    MetricChannelProvider,
    MetricUpdate,
    ReferenceImageBatchSemantics,
    ScalarMetric,
    TrainingStrategy,
    TrainStepOutput,
    loss_aggregation_weight_to_float,
    validate_train_step_output,
)
from .trainer import Trainer
from .validation import (
    EpochValidationCadence,
    EpochValidationEvaluator,
    EpochValidationIdentity,
    EpochValidationResult,
)

__all__ = [
    "PRECISION_KINDS",
    "Batch",
    "CheckpointSelectionKind",
    "ClassConditionalDiffusionQualityDiagnostic",
    "ClassConditionalGaussianDenoisingTrainingBuilder",
    "ClassConditionalGaussianDenoisingTrainingStrategy",
    "ClassConditionalGaussianDiagnosticSemantics",
    "ClassConditionalGaussianStepObservation",
    "ContextAwareDiagnostic",
    "DeviceTransferableBatch",
    "DiagnosticBuildContext",
    "DiagnosticModelAccess",
    "EpochValidationCadence",
    "EpochValidationEvaluator",
    "EpochValidationIdentity",
    "EpochValidationResult",
    "ExponentialMovingAverage",
    "FinalSummary",
    "FitStartEvent",
    "GaussianDenoisingTrainingBuilder",
    "GaussianDenoisingTrainingStrategy",
    "GaussianDiagnosticSemantics",
    "GaussianStepObservation",
    "InferenceAssetProjection",
    "MSEObjective",
    "ManagedTrainingModule",
    "MetricChannelProvider",
    "MetricUpdate",
    "PerSampleObjective",
    "PrecisionKind",
    "PrecisionRuntime",
    "ReferenceImageBatchSemantics",
    "RichTrainingReporter",
    "RunSummary",
    "ScalarMetric",
    "SupervisedTrainingBuilder",
    "SupervisedTrainingStrategy",
    "TrainBatchEndEvent",
    "TrainEpochEndEvent",
    "TrainStepOutput",
    "Trainer",
    "TrainingBuilder",
    "TrainingBuilderContext",
    "TrainingDiagnostic",
    "TrainingExecutionBindingBuilder",
    "TrainingPlan",
    "TrainingPlanAssembly",
    "TrainingRunOutcome",
    "TrainingStrategy",
    "WarmupCosineLR",
    "build_precision_runtime",
    "build_training_plan",
    "build_training_plan_assembly",
    "compute_objective",
    "gaussian_training_target",
    "loss_aggregation_weight_to_float",
    "trainable_parameters",
    "training_module_roots",
    "validate_precision_support",
    "validate_train_step_output",
    "validate_training_plan",
]
